---

- name: Install packages via pip
  sudo: yes
  pip: name="{{ item.name }}" version="{{ item.version }}"
  when: superslacker_pip_dependencies is defined
  with_items: superslacker_pip_dependencies
